if (!document.localization) document.localization = [];

(function () {
    var defaults = {
        'tab.gpsmap': 'Maps / GPS',
        'breadcrumb.gpsmap': 'Maps / GPS',
        'gpsmap.title': 'Maps / GPS',
        'gpsmap.fit.all': 'Fit all',
        'gpsmap.popup.updated': 'Updated',
        'gpsmap.error.load.failed': 'Failed to load device locations',
        'gpsmap.all.groups': 'All groups',
        'gpsmap.empty': 'No device has reported a GPS location yet.',
        'gpsmap.error.render': 'Map could not be loaded.',
        'gpsmap.devices.on.map': 'device(s) on map',
        'gpsmap.updated.at': 'Updated at',
        'gpsmap.auto.refresh': 'auto-refresh',
        'gpsmap.refresh.30s': 'Refresh every 30s',
        'gpsmap.refresh.60s': 'Refresh every 1 min',
        'gpsmap.refresh.off': 'Auto-refresh off',
        'tab.chat': 'Chat',
        'breadcrumb.chat': 'Chat',
        'chat.title': 'Device chat',
        'chat.history.title': 'Message history',
        'chat.no.permission': 'No permission for chat',
        'chat.error.load.failed': 'Failed to load messages',
        'chat.error.send.failed': 'Failed to send the message',
        'chat.error.message.too.long': 'Message is too long (max 5000 characters)',
        'format.date.plugin.messaging.createTime': 'dd/MM/yyyy HH:mm:ss',
        'plugin.messaging.label.device': 'Device',
        'plugin.messaging.label.message': 'Message text',
        'plugin.messaging.button.send': 'Send',
        'plugin.messaging.error.empty.device': 'Please select the device receiving the message',
        'plugin.messaging.error.empty.text': 'Message text cannot be empty',
        'plugin.messaging.error.empty.request': 'Message request cannot be empty',
        'plugin.messaging.error.invalid.scope': 'Message destination is invalid',
        'plugin.messaging.error.text.too.long': 'Message is too long (max 5000 characters)',
        'plugin.messaging.status.sent': 'Sent',
        'plugin.messaging.status.delivered': 'Delivered',
        'plugin.messaging.status.read': 'Read',
        'plugin.messaging.send.success': 'The message has been sent',
        'notfound.common.plugin.messaging.messages': 'No messages yet',
        'button.refresh': 'Refresh',
        'permission.device.gps.view': 'View GPS map',
        'summary.alert.offline': 'Device offline',

        // --- Remote access: server-driven command palette -------------------------------
        // Returned verbatim by POST rest/private/devices/{id}/command when the server build
        // has no implementation for the requested action.
        'error.remote.command.unsupported': 'This server build does not support that action.',
        'remote.error.catalog.failed': 'Could not read the list of supported actions from the server.',
        'remote.error.field.required': '${field} is required.',
        'remote.error.field.invalid': '${field} is not valid.',
        'remote.error.field.pkg': 'Package name must look like com.example.app.',
        'remote.error.field.path': 'Path must be absolute and must not contain "..".',
        'remote.error.field.intent.action': 'Intent action may only contain letters, digits, dots and underscores.',
        'remote.error.field.duration': 'Duration must be between 1 and 3600 seconds.',
        'remote.group.session': 'Screen & session',
        'remote.group.lifecycle': 'Device lifecycle',
        'remote.group.apps': 'Applications',
        'remote.group.storage': 'Files & storage',
        'remote.group.advanced': 'Advanced',
        'remote.group.other': 'Other actions',
        'remote.field.text': 'Message text',
        'remote.field.duration': 'Show for (seconds)',
        'remote.field.pkg': 'Package name',
        'remote.field.path': 'Path on the device',
        'remote.field.command': 'Shell command',
        'remote.field.intent.action': 'Intent action',
        'remote.field.intent.data': 'Intent data',
        'remote.field.externalstorage': 'Also wipe external storage',
        'button.remote.adminpanel': 'Open admin panel',
        'button.remote.grant': 'Re-grant permissions',
        'button.remote.permissive': 'Permissive mode',
        'button.remote.runapp': 'Launch app',
        'button.remote.uninstallapp': 'Uninstall app',
        'button.remote.clearappdata': 'Clear app data',
        'button.remote.deletefile': 'Delete file',
        'button.remote.deletedir': 'Delete folder',
        'button.remote.purgedir': 'Empty folder',
        'button.remote.cleardownloads': 'Clear download history',
        'button.remote.runcommand': 'Run shell command',
        'button.remote.intent': 'Send intent',
        'button.remote.broadcast': 'Send broadcast',

        // --- Navigation ------------------------------------------------------------------
        // The reworked panel had its menu and page headings written as literals in the
        // templates, so they stayed English while every legacy screen followed the language
        // configured in Server defaults. They are resource keys now, which is what makes the
        // language setting apply to the whole panel instead of half of it.
        'nav.menu': 'Menu',
        'nav.brand.control.panel': 'Control panel',
        'nav.group.fleet': 'Fleet',
        'nav.group.delivery': 'Delivery to devices',
        'nav.group.server': 'Server',
        'nav.dashboard': 'Dashboard',
        'nav.devices': 'Devices',
        'nav.kiosk': 'Kiosk',
        'nav.gpsmap': 'Location map',
        'nav.remote': 'Remote access',
        'nav.chat': 'Messages',
        'nav.reports': 'Reports',
        'nav.configurations': 'Device profiles',
        'nav.applications': 'Applications',
        'nav.files': 'Files',
        'nav.icons': 'Launcher icons',
        'nav.users': 'Panel users',
        'nav.roles': 'Permissions',
        'nav.groups': 'Device groups',
        'nav.common': 'Device list columns',
        'nav.design': 'Appearance & branding',
        'nav.general': 'Server defaults',
        'nav.extensions': 'Plugins',
        'nav.governance': 'Backup & restore',

        // Page headings reuse the nav.* key of the sidebar entry that opens them, so the
        // title and the menu item cannot drift apart again. Only the subtitle is per-screen.
        'dashboard.page.subtitle': 'Fleet status at a glance: enrollment, last known locations and open alerts.',
        'devices.page.subtitle': 'Device inventory, enrollment state, remote actions and operational filtering.',
        'gpsmap.page.subtitle': 'Live map with the last location reported by each device.',
        'remote.page.subtitle': 'Pick a device, send an action, and open a screenshot session when the agent supports it.',
        'configurations.page.subtitle': 'Device enrollment profiles, kiosk policy, application set and QR provisioning.',
        'governance.page.subtitle': 'Export settings, import a saved setup, and manage database backups from one place.',
        'icons.page.subtitle': 'Icons available to the launcher shown on the managed devices.',
        'users.page.subtitle': 'Accounts that can sign in to this console, and the role each one carries.',
        'roles.page.subtitle': 'Roles and what each role is allowed to do in this console.',
        'groups.page.subtitle': 'Groups used to filter the device list and to scope what a user may see.',
        'common.page.subtitle': 'Choose which columns appear in the Devices list for each role.',

        // --- Kiosk -----------------------------------------------------------------------
        'kiosk.page.subtitle': 'Dedicated control surface for restricted tablets, allowed apps, MDM APK, GPS and remote apply.',
        'kiosk.save.profile': 'Save kiosk profile',
        'kiosk.status.profile': 'Profile',
        'kiosk.status.profile.policy': 'Kiosk mode (profile policy)',
        'kiosk.status.device.state': 'Kiosk state (reported by device)',
        'kiosk.status.launch.app': 'Launch app',
        'kiosk.status.allowed.apps': 'Allowed apps',
        'kiosk.status.devices': 'Devices on profile',
        'kiosk.policy.enabled': 'Enabled',
        'kiosk.policy.disabled': 'Disabled',
        'kiosk.device.state.locked': 'Locked',
        'kiosk.device.state.unlocked': 'Not locked',
        'kiosk.device.state.unknown': 'Not reported',
        'kiosk.device.state.unknown.hint': 'The device has not checked in yet.',
        'kiosk.device.state.pending.hint': 'The profile requires kiosk; not applied on the device yet.',
        'kiosk.devices.title': 'Devices locked by this profile',
        'kiosk.devices.empty': 'No devices use this profile.',
        'kiosk.open.remote': 'Open remote access',
        'kiosk.col.device': 'Device',
        'kiosk.col.status': 'Status',
        'kiosk.col.android': 'Android',
        'kiosk.col.ip': 'Device IP',
        'kiosk.col.actions': 'Actions',
        'kiosk.action.force': 'Force kiosk',
        'kiosk.action.push': 'Push config',
        'kiosk.apply.strict': 'Apply maximum restriction',
        'kiosk.tab.devices': 'Devices',
        'kiosk.tab.lockdown': 'Lockdown policy',
        'kiosk.tab.apps': 'Allowed apps',
        'kiosk.tab.agent': 'MDM APK',
        'kiosk.tab.location': 'GPS',
        'kiosk.tab.apply': 'Apply',
        'kiosk.sw.enabled': 'Kiosk enabled',
        'kiosk.sw.home': 'Home allowed',
        'kiosk.sw.recents': 'Recents allowed',
        'kiosk.sw.notifications': 'Notifications allowed',
        'kiosk.sw.exit': 'Exit allowed',
        'kiosk.sw.buttons': 'Hardware buttons locked',
        'kiosk.sw.screenon': 'Keep screen awake',
        'kiosk.sw.safesettings': 'Lock safe settings',
        'kiosk.sw.gps': 'GPS enabled',
        'kiosk.sw.disable.location': 'Disable location on device',
        'kiosk.sw.block.location': 'Block location sharing',
        'kiosk.apps.hint': 'Install the app, then allow it in kiosk. Everything else remains blocked.',
        'kiosk.col.application': 'Application',
        'kiosk.col.version': 'Version',
        'kiosk.col.install': 'Install',
        'kiosk.col.allow': 'Allow in kiosk',
        'kiosk.col.launch': 'Launch app',
        'kiosk.col.url': 'URL',
        'kiosk.col.action': 'Action',
        'kiosk.app.installed': 'Installed by profile',
        'kiosk.app.not.installed': 'Do not install',
        'kiosk.app.allowed': 'Allowed',
        'kiosk.app.blocked': 'Blocked',
        'kiosk.app.use.launch': 'Use as launch app',
        'kiosk.agent.use.newest': 'Use newest APK',
        'kiosk.agent.current': 'Current agent',
        'kiosk.agent.selected': 'Selected',
        'kiosk.agent.select': 'Select APK',
        'kiosk.agent.none': 'No MDM agent APK in this profile',
        'kiosk.launch.app.none': 'No launch app selected',
        'kiosk.save.feedback': 'Kiosk profile saved and queued for devices.',
        'kiosk.apply.save.notify': 'Save and notify',
        'kiosk.status.blocked.apps': 'Blocked apps',
        'kiosk.gps.mode': 'Tracking mode',
        'kiosk.gps.donottrack': 'Do not track',
        'kiosk.gps.network': 'Network',
        'kiosk.gps.both': 'GPS and network',
        'kiosk.gps.permissions': 'App permissions',
        'kiosk.perm.grantall': 'Grant all',
        'kiosk.perm.ask': 'Ask',
        'kiosk.perm.denylocation': 'Deny location',

        // --- Messages --------------------------------------------------------------------
        'chat.page.subtitle': 'Send a message to a device and review what has already been delivered.',
        'chat.device.select.placeholder': 'Select a device',
        'chat.device.select.empty': 'No device is enrolled yet.',

        // --- Reports ---------------------------------------------------------------------
        'reports.page.subtitle': 'Fleet composition, health and app inventory, computed live from the current device list.',
        'reports.devices.generated': 'devices · generated',
        'reports.export.csv': 'Export CSV',
        'reports.empty': 'No devices enrolled yet.',
        'reports.section.status': 'Status',
        'reports.section.android': 'Android version',
        'reports.section.battery': 'Battery health',
        'reports.section.storage': 'Storage health',
        'reports.section.models': 'Device models',
        'reports.section.apps': 'Most installed apps',
        'reports.apps.hint': 'Share of the fleet with each application installed (top 20). Network data-usage telemetry is not collected by the launcher yet, so it cannot be shown here.',
        'reports.empty.android': 'No Android version data reported yet.',
        'reports.empty.battery': 'No battery data reported yet.',
        'reports.empty.storage': 'No storage data reported yet.',
        'reports.empty.models': 'No model data reported yet.',
        'reports.empty.apps': 'No application inventory reported yet.',

        // --- Device profile editor -------------------------------------------------------
        'cfg.step.basics': 'Profile basics',
        'cfg.step.apps': 'Apps delivered to the device',
        'cfg.step.agent': 'Agent & kiosk behaviour',
        'cfg.step.appsettings': 'Per-app settings',
        'cfg.step.files': 'Files pushed to the device',
        'cfg.step.design': 'Home screen appearance',
        'cfg.savebar.note': 'Saving applies every section of this profile, not only the one on screen.',

        // --- Settings --------------------------------------------------------------------
        'settings.design.title': 'Appearance & branding',
        'settings.design.subtitle': 'Colours and logo of this web console.',
        'settings.design.console.title': 'Web console',
        'settings.design.console.subtitle': 'Panel appearance stored in the server settings.',
        'settings.design.console.primary.color': 'Primary colour',
        'settings.design.console.primary.color.hint': 'Buttons, links and the active menu entry.',
        'settings.design.console.sidebar.color': 'Sidebar colour',
        'settings.design.console.sidebar.color.hint': 'Background of the side menu.',
        'settings.design.console.text.color': 'Text colour',
        'settings.design.console.text.color.hint': 'Main text of the panel and of the menu.',
        'settings.design.console.logo': 'Console logo',
        'settings.design.console.logo.choose': 'Choose file',
        'settings.design.console.logo.hint': 'Empty keeps the Headwind MDM brand. Any aspect ratio works: the logo is scaled by height.',
        'settings.design.console.logo.preview': 'Preview',
        'settings.design.launcher.moved.title': 'Tablet home screen',
        'settings.design.launcher.moved.body': 'The launcher theme sent to the tablets (background, icon size, desktop title) belongs to a device profile. Edit it in step 6, "Home screen appearance", of the profile.',
        'settings.design.launcher.moved.action': 'Open device profiles',
        'settings.general.title': 'Server defaults',
        'settings.general.subtitle': 'Language, custom device fields, security policy and default behavior for new enrollments.',
        'settings.general.new.device.defaults': 'New device defaults',
        'form.settings.lang.use.default.hint': 'The panel follows the browser language. Untick to choose one.'
    };

    var pt = {
        'tab.gpsmap': 'Mapas / GPS',
        'breadcrumb.gpsmap': 'Mapas / GPS',
        'gpsmap.title': 'Mapas / GPS',
        'gpsmap.fit.all': 'Ajustar todos',
        'gpsmap.popup.updated': 'Atualizado',
        'gpsmap.error.load.failed': 'Falha ao carregar as localizações dos dispositivos',
        'gpsmap.all.groups': 'Todos os grupos',
        'gpsmap.empty': 'Nenhum dispositivo enviou localização GPS ainda.',
        'gpsmap.error.render': 'Não foi possível carregar o mapa.',
        'gpsmap.devices.on.map': 'dispositivo(s) no mapa',
        'gpsmap.updated.at': 'Atualizado às',
        'gpsmap.auto.refresh': 'atualização automática',
        'gpsmap.refresh.30s': 'Atualizar a cada 30s',
        'gpsmap.refresh.60s': 'Atualizar a cada 1 min',
        'gpsmap.refresh.off': 'Atualização automática desligada',
        'tab.chat': 'Chat',
        'breadcrumb.chat': 'Chat',
        'chat.title': 'Chat com dispositivo',
        'chat.history.title': 'Histórico de mensagens',
        'chat.no.permission': 'Sem permissão para chat',
        'chat.error.load.failed': 'Falha ao carregar mensagens',
        'chat.error.send.failed': 'Falha ao enviar a mensagem',
        'chat.error.message.too.long': 'Mensagem muito longa (máx. 5000 caracteres)',
        'plugin.messaging.label.device': 'Dispositivo',
        'plugin.messaging.label.message': 'Mensagem',
        'plugin.messaging.button.send': 'Enviar',
        'plugin.messaging.error.empty.device': 'Selecione o dispositivo que vai receber a mensagem',
        'plugin.messaging.error.empty.text': 'A mensagem não pode ser vazia',
        'plugin.messaging.error.empty.request': 'A requisição da mensagem não pode ser vazia',
        'plugin.messaging.error.invalid.scope': 'O destino da mensagem é inválido',
        'plugin.messaging.error.text.too.long': 'Mensagem muito longa (máx. 5000 caracteres)',
        'plugin.messaging.status.sent': 'Enviada',
        'plugin.messaging.status.delivered': 'Entregue',
        'plugin.messaging.status.read': 'Lida',
        'plugin.messaging.send.success': 'A mensagem foi enviada',
        'notfound.common.plugin.messaging.messages': 'Sem mensagens',
        'button.refresh': 'Atualizar',
        'permission.device.gps.view': 'Visualizar mapa GPS',
        'summary.alert.offline': 'Dispositivo offline',

        'error.remote.command.unsupported': 'Esta versao do servidor nao suporta essa acao.',
        'remote.error.catalog.failed': 'Nao foi possivel ler no servidor a lista de acoes suportadas.',
        'remote.error.field.required': '${field} e obrigatorio.',
        'remote.error.field.invalid': '${field} nao e valido.',
        'remote.error.field.pkg': 'O nome do pacote deve ser no formato com.exemplo.app.',
        'remote.error.field.path': 'O caminho deve ser absoluto e nao pode conter "..".',
        'remote.error.field.intent.action': 'A acao do intent so aceita letras, numeros, pontos e underscore.',
        'remote.error.field.duration': 'A duracao deve ficar entre 1 e 3600 segundos.',
        'remote.group.session': 'Tela e sessao',
        'remote.group.lifecycle': 'Ciclo de vida do dispositivo',
        'remote.group.apps': 'Aplicativos',
        'remote.group.storage': 'Arquivos e armazenamento',
        'remote.group.advanced': 'Avancado',
        'remote.group.other': 'Outras acoes',
        'remote.field.text': 'Texto da mensagem',
        'remote.field.duration': 'Exibir por (segundos)',
        'remote.field.pkg': 'Nome do pacote',
        'remote.field.path': 'Caminho no dispositivo',
        'remote.field.command': 'Comando shell',
        'remote.field.intent.action': 'Acao do intent',
        'remote.field.intent.data': 'Dados do intent',
        'remote.field.externalstorage': 'Apagar tambem o armazenamento externo',
        'button.remote.adminpanel': 'Abrir painel de administracao',
        'button.remote.grant': 'Reconceder permissoes',
        'button.remote.permissive': 'Modo permissivo',
        'button.remote.runapp': 'Abrir aplicativo',
        'button.remote.uninstallapp': 'Desinstalar aplicativo',
        'button.remote.clearappdata': 'Limpar dados do aplicativo',
        'button.remote.deletefile': 'Excluir arquivo',
        'button.remote.deletedir': 'Excluir pasta',
        'button.remote.purgedir': 'Esvaziar pasta',
        'button.remote.cleardownloads': 'Limpar historico de downloads',
        'button.remote.runcommand': 'Executar comando shell',
        'button.remote.intent': 'Enviar intent',
        'button.remote.broadcast': 'Enviar broadcast',

        // --- Navegacao -------------------------------------------------------------------
        'nav.menu': 'Menu',
        'nav.brand.control.panel': 'Painel de controle',
        'nav.group.fleet': 'Frota',
        'nav.group.delivery': 'Entrega aos dispositivos',
        'nav.group.server': 'Servidor',
        'nav.dashboard': 'Painel',
        'nav.devices': 'Dispositivos',
        'nav.kiosk': 'Quiosque',
        'nav.gpsmap': 'Mapa de localizacao',
        'nav.remote': 'Acesso remoto',
        'nav.chat': 'Mensagens',
        'nav.reports': 'Relatorios',
        'nav.configurations': 'Perfis de dispositivo',
        'nav.applications': 'Aplicativos',
        'nav.files': 'Arquivos',
        'nav.icons': 'Icones do launcher',
        'nav.users': 'Usuarios do painel',
        'nav.roles': 'Permissoes',
        'nav.groups': 'Grupos de dispositivos',
        'nav.common': 'Colunas da lista de dispositivos',
        'nav.design': 'Aparencia e marca',
        'nav.general': 'Padroes do servidor',
        'nav.extensions': 'Plugins',
        'nav.governance': 'Backup e restauracao',

        'dashboard.page.subtitle': 'Situacao da frota num relance: inscricao, ultimas localizacoes e alertas abertos.',
        'devices.page.subtitle': 'Inventario de dispositivos, estado de inscricao, acoes remotas e filtros operacionais.',
        'gpsmap.page.subtitle': 'Mapa em tempo real com a ultima localizacao reportada por cada dispositivo.',
        'remote.page.subtitle': 'Escolha um dispositivo, envie uma acao e abra uma sessao de tela quando o agente suportar.',
        'configurations.page.subtitle': 'Perfis de inscricao, politica de quiosque, conjunto de apps e provisionamento por QR.',
        'governance.page.subtitle': 'Exporte configuracoes, importe um setup salvo e gerencie backups do banco em um so lugar.',
        'icons.page.subtitle': 'Icones disponiveis para o launcher exibido nos dispositivos gerenciados.',
        'users.page.subtitle': 'Contas que podem entrar neste console e o papel de cada uma.',
        'roles.page.subtitle': 'Papeis e o que cada papel pode fazer neste console.',
        'groups.page.subtitle': 'Grupos usados para filtrar a lista de dispositivos e limitar o que um usuario ve.',
        'common.page.subtitle': 'Escolha quais colunas aparecem na lista de dispositivos para cada papel.',

        // --- Quiosque --------------------------------------------------------------------
        'kiosk.page.subtitle': 'Controle dedicado de tablets restritos: apps permitidos, APK do MDM, GPS e aplicacao remota.',
        'kiosk.save.profile': 'Salvar perfil de quiosque',
        'kiosk.status.profile': 'Perfil',
        'kiosk.status.profile.policy': 'Modo quiosque (politica do perfil)',
        'kiosk.status.device.state': 'Estado do quiosque (informado pelo dispositivo)',
        'kiosk.status.launch.app': 'App inicial',
        'kiosk.status.allowed.apps': 'Apps permitidos',
        'kiosk.status.devices': 'Dispositivos no perfil',
        'kiosk.policy.enabled': 'Ativado',
        'kiosk.policy.disabled': 'Desativado',
        'kiosk.device.state.locked': 'Bloqueado',
        'kiosk.device.state.unlocked': 'Nao bloqueado',
        'kiosk.device.state.unknown': 'Sem informacao',
        'kiosk.device.state.unknown.hint': 'O dispositivo ainda nao se conectou.',
        'kiosk.device.state.pending.hint': 'O perfil exige quiosque; ainda nao aplicado no dispositivo.',
        'kiosk.devices.title': 'Dispositivos bloqueados por este perfil',
        'kiosk.devices.empty': 'Nenhum dispositivo usa este perfil.',
        'kiosk.open.remote': 'Abrir acesso remoto',
        'kiosk.col.device': 'Dispositivo',
        'kiosk.col.status': 'Status',
        'kiosk.col.android': 'Android',
        'kiosk.col.ip': 'IP do dispositivo',
        'kiosk.col.actions': 'Acoes',
        'kiosk.action.force': 'Forcar quiosque',
        'kiosk.action.push': 'Enviar configuracao',
        'kiosk.apply.strict': 'Aplicar restricao maxima',
        'kiosk.tab.devices': 'Dispositivos',
        'kiosk.tab.lockdown': 'Politica de bloqueio',
        'kiosk.tab.apps': 'Apps permitidos',
        'kiosk.tab.agent': 'APK do MDM',
        'kiosk.tab.location': 'GPS',
        'kiosk.tab.apply': 'Aplicar',
        'kiosk.sw.enabled': 'Quiosque ativado',
        'kiosk.sw.home': 'Botao Home permitido',
        'kiosk.sw.recents': 'Recentes permitido',
        'kiosk.sw.notifications': 'Notificacoes permitidas',
        'kiosk.sw.exit': 'Saida permitida',
        'kiosk.sw.buttons': 'Botoes fisicos bloqueados',
        'kiosk.sw.screenon': 'Manter tela ligada',
        'kiosk.sw.safesettings': 'Bloquear configuracoes seguras',
        'kiosk.sw.gps': 'GPS ativado',
        'kiosk.sw.disable.location': 'Desativar localizacao no dispositivo',
        'kiosk.sw.block.location': 'Bloquear compartilhamento de localizacao',
        'kiosk.apps.hint': 'Instale o app e depois permita-o no quiosque. Todo o resto continua bloqueado.',
        'kiosk.col.application': 'Aplicativo',
        'kiosk.col.version': 'Versao',
        'kiosk.col.install': 'Instalar',
        'kiosk.col.allow': 'Permitir no quiosque',
        'kiosk.col.launch': 'App inicial',
        'kiosk.col.url': 'URL',
        'kiosk.col.action': 'Acao',
        'kiosk.app.installed': 'Instalado pelo perfil',
        'kiosk.app.not.installed': 'Nao instalar',
        'kiosk.app.allowed': 'Permitido',
        'kiosk.app.blocked': 'Bloqueado',
        'kiosk.app.use.launch': 'Usar como app inicial',
        'kiosk.agent.use.newest': 'Usar o APK mais novo',
        'kiosk.agent.current': 'Agente atual',
        'kiosk.agent.selected': 'Selecionado',
        'kiosk.agent.select': 'Selecionar APK',
        'kiosk.agent.none': 'Nenhum APK do agente MDM neste perfil',
        'kiosk.launch.app.none': 'Nenhum app inicial selecionado',
        'kiosk.save.feedback': 'Perfil de quiosque salvo e enfileirado para os dispositivos.',
        'kiosk.apply.save.notify': 'Salvar e notificar',
        'kiosk.status.blocked.apps': 'Apps bloqueados',
        'kiosk.gps.mode': 'Modo de rastreamento',
        'kiosk.gps.donottrack': 'Nao rastrear',
        'kiosk.gps.network': 'Rede',
        'kiosk.gps.both': 'GPS e rede',
        'kiosk.gps.permissions': 'Permissoes dos apps',
        'kiosk.perm.grantall': 'Conceder todas',
        'kiosk.perm.ask': 'Perguntar',
        'kiosk.perm.denylocation': 'Negar localizacao',

        // --- Mensagens -------------------------------------------------------------------
        'chat.page.subtitle': 'Envie uma mensagem a um dispositivo e veja o que ja foi entregue.',
        'chat.device.select.placeholder': 'Selecione um dispositivo',
        'chat.device.select.empty': 'Nenhum dispositivo cadastrado ainda.',

        // --- Relatorios ------------------------------------------------------------------
        'reports.page.subtitle': 'Composicao da frota, saude e inventario de apps, calculados a partir da lista atual de dispositivos.',
        'reports.devices.generated': 'dispositivos · gerado em',
        'reports.export.csv': 'Exportar CSV',
        'reports.empty': 'Nenhum dispositivo cadastrado ainda.',
        'reports.section.status': 'Status',
        'reports.section.android': 'Versao do Android',
        'reports.section.battery': 'Saude da bateria',
        'reports.section.storage': 'Saude do armazenamento',
        'reports.section.models': 'Modelos de dispositivo',
        'reports.section.apps': 'Apps mais instalados',
        'reports.apps.hint': 'Percentual da frota com cada aplicativo instalado (top 20). O launcher ainda nao coleta telemetria de uso de dados de rede, entao isso nao pode ser exibido aqui.',
        'reports.empty.android': 'Nenhum dado de versao do Android informado ainda.',
        'reports.empty.battery': 'Nenhum dado de bateria informado ainda.',
        'reports.empty.storage': 'Nenhum dado de armazenamento informado ainda.',
        'reports.empty.models': 'Nenhum dado de modelo informado ainda.',
        'reports.empty.apps': 'Nenhum inventario de aplicativos informado ainda.',

        // --- Editor de perfil ------------------------------------------------------------
        'cfg.step.basics': 'Basico do perfil',
        'cfg.step.apps': 'Apps entregues ao dispositivo',
        'cfg.step.agent': 'Agente e comportamento do quiosque',
        'cfg.step.appsettings': 'Configuracoes por app',
        'cfg.step.files': 'Arquivos enviados ao dispositivo',
        'cfg.step.design': 'Aparencia da tela inicial',
        'cfg.savebar.note': 'Salvar aplica todas as secoes deste perfil, nao apenas a que esta na tela.',

        // --- Configuracoes ---------------------------------------------------------------
        'settings.design.title': 'Aparencia e marca',
        'settings.design.subtitle': 'Cores e logo deste painel web.',
        'settings.design.console.title': 'Console web',
        'settings.design.console.subtitle': 'Aparencia do painel salva nas configuracoes do servidor.',
        'settings.design.console.primary.color': 'Cor principal',
        'settings.design.console.primary.color.hint': 'Botoes, links e item ativo do menu.',
        'settings.design.console.sidebar.color': 'Cor da lateral',
        'settings.design.console.sidebar.color.hint': 'Fundo do menu lateral.',
        'settings.design.console.text.color': 'Cor do texto',
        'settings.design.console.text.color.hint': 'Texto principal do painel e do menu.',
        'settings.design.console.logo': 'Logo do console',
        'settings.design.console.logo.choose': 'Escolher arquivo',
        'settings.design.console.logo.hint': 'Vazio mantem a marca Headwind MDM. Qualquer proporcao serve: o logo e ajustado pela altura.',
        'settings.design.console.logo.preview': 'Previa',
        'settings.design.launcher.moved.title': 'Tela inicial do tablet',
        'settings.design.launcher.moved.body': 'O tema do launcher enviado aos tablets (fundo, tamanho dos icones, titulo da area de trabalho) pertence ao perfil de dispositivo. Edite no passo 6, "Aparencia da tela inicial", do perfil.',
        'settings.design.launcher.moved.action': 'Abrir perfis de dispositivo',
        'settings.general.title': 'Padroes do servidor',
        'settings.general.subtitle': 'Idioma, campos personalizados, politica de seguranca e comportamento padrao para novos cadastros.',
        'settings.general.new.device.defaults': 'Padroes de novo dispositivo',
        'form.settings.lang.use.default.hint': 'O painel segue o idioma do navegador. Desmarque para escolher um.'
    };

    var apply = function (locale, values, overwrite) {
        if (!document.localization[locale]) {
            document.localization[locale] = {};
        }
        Object.keys(values).forEach(function (key) {
            if (overwrite || !document.localization[locale][key]) {
                document.localization[locale][key] = values[key];
            }
        });
    };

    Object.keys(document.localization).forEach(function (locale) {
        apply(locale, defaults, false);
    });
    apply('pt_PT', pt, true);
})();
