if (!document.localization) document.localization = [];

(function () {
    var defaults = {
        'tab.gpsmap': 'Maps / GPS',
        'breadcrumb.gpsmap': 'Maps / GPS',
        'gpsmap.title': 'Maps / GPS',
        'gpsmap.fit.all': 'Fit all',
        'gpsmap.popup.updated': 'Updated',
        'gpsmap.error.load.failed': 'Failed to load device locations',
        'gpsmap.all.groups': 'All groups',
        'gpsmap.empty': 'No device has reported a GPS location yet.',
        'gpsmap.error.render': 'Map could not be loaded.',
        'gpsmap.devices.on.map': 'device(s) on map',
        'gpsmap.updated.at': 'Updated at',
        'gpsmap.auto.refresh': 'auto-refresh',
        'gpsmap.refresh.30s': 'Refresh every 30s',
        'gpsmap.refresh.60s': 'Refresh every 1 min',
        'gpsmap.refresh.off': 'Auto-refresh off',
        'tab.chat': 'Chat',
        'breadcrumb.chat': 'Chat',
        'chat.title': 'Device chat',
        'chat.history.title': 'Message history',
        'chat.no.permission': 'No permission for chat',
        'chat.error.load.failed': 'Failed to load messages',
        'chat.error.send.failed': 'Failed to send the message',
        'chat.error.message.too.long': 'Message is too long (max 5000 characters)',
        'format.date.plugin.messaging.createTime': 'dd/MM/yyyy HH:mm:ss',
        'plugin.messaging.label.device': 'Device',
        'plugin.messaging.label.message': 'Message text',
        'plugin.messaging.button.send': 'Send',
        'plugin.messaging.error.empty.device': 'Please select the device receiving the message',
        'plugin.messaging.error.empty.text': 'Message text cannot be empty',
        'plugin.messaging.error.empty.request': 'Message request cannot be empty',
        'plugin.messaging.error.invalid.scope': 'Message destination is invalid',
        'plugin.messaging.error.text.too.long': 'Message is too long (max 5000 characters)',
        'plugin.messaging.status.sent': 'Sent',
        'plugin.messaging.status.delivered': 'Delivered',
        'plugin.messaging.status.read': 'Read',
        'plugin.messaging.send.success': 'The message has been sent',
        'notfound.common.plugin.messaging.messages': 'No messages yet',
        'button.refresh': 'Refresh',
        'permission.device.gps.view': 'View GPS map',
        'summary.alert.offline': 'Device offline',

        // --- Remote access: server-driven command palette -------------------------------
        // Returned verbatim by POST rest/private/devices/{id}/command when the server build
        // has no implementation for the requested action.
        'error.remote.command.unsupported': 'This server build does not support that action.',
        'remote.error.catalog.failed': 'Could not read the list of supported actions from the server.',
        'remote.error.field.required': '${field} is required.',
        'remote.error.field.invalid': '${field} is not valid.',
        'remote.error.field.pkg': 'Package name must look like com.example.app.',
        'remote.error.field.path': 'Path must be absolute and must not contain "..".',
        'remote.error.field.intent.action': 'Intent action may only contain letters, digits, dots and underscores.',
        'remote.error.field.duration': 'Duration must be between 1 and 3600 seconds.',
        'remote.group.session': 'Screen & session',
        'remote.group.lifecycle': 'Device lifecycle',
        'remote.group.apps': 'Applications',
        'remote.group.storage': 'Files & storage',
        'remote.group.advanced': 'Advanced',
        'remote.group.other': 'Other actions',
        'remote.field.text': 'Message text',
        'remote.field.duration': 'Show for (seconds)',
        'remote.field.pkg': 'Package name',
        'remote.field.path': 'Path on the device',
        'remote.field.command': 'Shell command',
        'remote.field.intent.action': 'Intent action',
        'remote.field.intent.data': 'Intent data',
        'remote.field.externalstorage': 'Also wipe external storage',
        'button.remote.adminpanel': 'Open admin panel',
        'button.remote.grant': 'Re-grant permissions',
        'button.remote.permissive': 'Permissive mode',
        'button.remote.runapp': 'Launch app',
        'button.remote.uninstallapp': 'Uninstall app',
        'button.remote.clearappdata': 'Clear app data',
        'button.remote.deletefile': 'Delete file',
        'button.remote.deletedir': 'Delete folder',
        'button.remote.purgedir': 'Empty folder',
        'button.remote.cleardownloads': 'Clear download history',
        'button.remote.runcommand': 'Run shell command',
        'button.remote.intent': 'Send intent',
        'button.remote.broadcast': 'Send broadcast'
    };

    var pt = {
        'tab.gpsmap': 'Mapas / GPS',
        'breadcrumb.gpsmap': 'Mapas / GPS',
        'gpsmap.title': 'Mapas / GPS',
        'gpsmap.fit.all': 'Ajustar todos',
        'gpsmap.popup.updated': 'Atualizado',
        'gpsmap.error.load.failed': 'Falha ao carregar as localizações dos dispositivos',
        'gpsmap.all.groups': 'Todos os grupos',
        'gpsmap.empty': 'Nenhum dispositivo enviou localização GPS ainda.',
        'gpsmap.error.render': 'Não foi possível carregar o mapa.',
        'gpsmap.devices.on.map': 'dispositivo(s) no mapa',
        'gpsmap.updated.at': 'Atualizado às',
        'gpsmap.auto.refresh': 'atualização automática',
        'gpsmap.refresh.30s': 'Atualizar a cada 30s',
        'gpsmap.refresh.60s': 'Atualizar a cada 1 min',
        'gpsmap.refresh.off': 'Atualização automática desligada',
        'tab.chat': 'Chat',
        'breadcrumb.chat': 'Chat',
        'chat.title': 'Chat com dispositivo',
        'chat.history.title': 'Histórico de mensagens',
        'chat.no.permission': 'Sem permissão para chat',
        'chat.error.load.failed': 'Falha ao carregar mensagens',
        'chat.error.send.failed': 'Falha ao enviar a mensagem',
        'chat.error.message.too.long': 'Mensagem muito longa (máx. 5000 caracteres)',
        'plugin.messaging.label.device': 'Dispositivo',
        'plugin.messaging.label.message': 'Mensagem',
        'plugin.messaging.button.send': 'Enviar',
        'plugin.messaging.error.empty.device': 'Selecione o dispositivo que vai receber a mensagem',
        'plugin.messaging.error.empty.text': 'A mensagem não pode ser vazia',
        'plugin.messaging.error.empty.request': 'A requisição da mensagem não pode ser vazia',
        'plugin.messaging.error.invalid.scope': 'O destino da mensagem é inválido',
        'plugin.messaging.error.text.too.long': 'Mensagem muito longa (máx. 5000 caracteres)',
        'plugin.messaging.status.sent': 'Enviada',
        'plugin.messaging.status.delivered': 'Entregue',
        'plugin.messaging.status.read': 'Lida',
        'plugin.messaging.send.success': 'A mensagem foi enviada',
        'notfound.common.plugin.messaging.messages': 'Sem mensagens',
        'button.refresh': 'Atualizar',
        'permission.device.gps.view': 'Visualizar mapa GPS',
        'summary.alert.offline': 'Dispositivo offline',

        'error.remote.command.unsupported': 'Esta versao do servidor nao suporta essa acao.',
        'remote.error.catalog.failed': 'Nao foi possivel ler no servidor a lista de acoes suportadas.',
        'remote.error.field.required': '${field} e obrigatorio.',
        'remote.error.field.invalid': '${field} nao e valido.',
        'remote.error.field.pkg': 'O nome do pacote deve ser no formato com.exemplo.app.',
        'remote.error.field.path': 'O caminho deve ser absoluto e nao pode conter "..".',
        'remote.error.field.intent.action': 'A acao do intent so aceita letras, numeros, pontos e underscore.',
        'remote.error.field.duration': 'A duracao deve ficar entre 1 e 3600 segundos.',
        'remote.group.session': 'Tela e sessao',
        'remote.group.lifecycle': 'Ciclo de vida do dispositivo',
        'remote.group.apps': 'Aplicativos',
        'remote.group.storage': 'Arquivos e armazenamento',
        'remote.group.advanced': 'Avancado',
        'remote.group.other': 'Outras acoes',
        'remote.field.text': 'Texto da mensagem',
        'remote.field.duration': 'Exibir por (segundos)',
        'remote.field.pkg': 'Nome do pacote',
        'remote.field.path': 'Caminho no dispositivo',
        'remote.field.command': 'Comando shell',
        'remote.field.intent.action': 'Acao do intent',
        'remote.field.intent.data': 'Dados do intent',
        'remote.field.externalstorage': 'Apagar tambem o armazenamento externo',
        'button.remote.adminpanel': 'Abrir painel de administracao',
        'button.remote.grant': 'Reconceder permissoes',
        'button.remote.permissive': 'Modo permissivo',
        'button.remote.runapp': 'Abrir aplicativo',
        'button.remote.uninstallapp': 'Desinstalar aplicativo',
        'button.remote.clearappdata': 'Limpar dados do aplicativo',
        'button.remote.deletefile': 'Excluir arquivo',
        'button.remote.deletedir': 'Excluir pasta',
        'button.remote.purgedir': 'Esvaziar pasta',
        'button.remote.cleardownloads': 'Limpar historico de downloads',
        'button.remote.runcommand': 'Executar comando shell',
        'button.remote.intent': 'Enviar intent',
        'button.remote.broadcast': 'Enviar broadcast'
    };

    var apply = function (locale, values, overwrite) {
        if (!document.localization[locale]) {
            document.localization[locale] = {};
        }
        Object.keys(values).forEach(function (key) {
            if (overwrite || !document.localization[locale][key]) {
                document.localization[locale][key] = values[key];
            }
        });
    };

    Object.keys(document.localization).forEach(function (locale) {
        apply(locale, defaults, false);
    });
    apply('pt_PT', pt, true);
})();
